_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 80
    NUM_KNOWN_TRAIN: 0
    NUM_KNOWN_TEST: 0

DATASETS:
  TRAIN: ("dentex_train",)
  TEST:  ("dentex_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: False
  FORMAT: "RGB"
